### ISSUE TITLE
example can't run 

### ISSUE THREAD

**Issue by kexul** [cdsgroup/resp#15]
By runing exmple1.py, Error raised.
`Traceback (most recent call last):
  File "aa.py", line 21, in <module>
    charges1 = resp.resp([mol], options)
  File "/root/anaconda3/envs/psi/lib/python3.7/site-packages/resp/driver.py", line 61, in resp
    options = {k.upper(): v for k, v in sorted(options_list[0].items())}
KeyError: 0
`

**Comment by alenaizan** [comment]
Thanks for pointing this out. The example files in the master branch work with the current code, which is more updated than the RESP code that you download with conda. I suggest that you install the current version of the code from GitHub so that it works with the example files. Just do:
```
git clone https://github.com/cdsgroup/resp.git
cd resp
python setup.py install
```

Alternatively, you can download old example files from the latest release 0.8.1: https://github.com/cdsgroup/resp/releases/tag/v0.8.1

@loriab Can we update the conda RESP package at some point?

**Comment by kexul** [comment]
Got it.
