### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by metma99** [cdsgroup/resp#4]
Hello:
Started to use your resp code and would like to thank you here at this point.
May ask if it is possible to use more than two conformers for resp charge fitting?
I found in your code a "GRID input option" which might be the answer here but thought I would ask you.
Keep up the good work.
Best,
Markus

**Comment by alenaizan** [comment]
Hi Markus,

Definitely, example 2 in `tests/test_resp.py` shows you how to do two conformers. Doing three conformers is straightforward. 
* Define the third conformer `mol3`
* Add it the molecule list `molecules = [mol1, mol2, mol3]`
* Add the intermolecular constraints, so that related atoms have identical charges, e.g.
```
intermolecular_constraint = {'EQUAL': [[[1, range(1, 10)], [2, range(1, 10)]],
                                       [[1, range(1, 10)], [3, range(1, 10)]]]}
```
* Add options for the third conformer `options = [options1, options2, options3]`

Then, call the resp code.

Let me know if you have any other questions.

**Comment by alenaizan** [comment]
The `grid` option is for users to provide their own grid points instead of using the grid generated in the code. It's useful, for example, in the two-stage fitting procedure, where you do not need to recompute the grid and electrostatic potential.
